[package]
name = "avgtime"
version = "0.3.0"
authors = ["Patrick Robinson <therealpatrobinson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.18"
threadpool = "1.8.1"
